# Site settings
title: HS Hackers NoVA
location: Northern Virginia
description: "Welcome to the High School Hackers NoVA meetup group!"
baseurl: ""
url: "http://nova.hshackers.org"

# More settings
accent: "#00C2E4"
twitter: "hshackersnova"
github: "hshackers/nova"
contact: "hello at victorlourng dot com"
organizers: "Daniel Christopher"

# Get Meetup Notifications, visible or hidden
notifications: "visible"

# Get Meetup Notifications, IFTTT recipie URLs
email: ""
gcal: ""
sms: ""
android: ""
ifttt: "http://ifttt.com/"

# Local Meetup Links
meetup1: "HS Hackers Philly"
meetup1-url: "http://hshackers.org/"
meetup2: ""
meetup2-url: ""
meetup3: ""
meetup3-url: ""

# Build settings
markdown: kramdown
permalink: pretty
